python -u main.py simulation -v -ld "" \
-p max_train_iter 400  \
-p data_folder "data" \
-p trainstage pretrain_baseFSCIL \
-p pretrainFC linear \
-p dataset cifar100 \
-p random_seed 7 \
-p learning_rate 0.01 \
-p batch_size 64 \
-p optimizer SGD \
-p SGDnesterov True \
-p lr_step_size 50 \
-p representation tanh \
-p dim_features 640 \
-p block_architecture mini_resnet12 \
-p sharpening_activation abs \
-p pcl_weight 1.0 \
-p gpu 0