python -u main.py simulation \
-v \
-ld ""  \
-p data_folder "data" \
-p resume "" \
-p dim_features 640 \
-p retrain_iter 150 \
-p nudging_iter 0 \
-p bipolarize_prototypes False \
-p nudging_act_exp 4 \
-p nudging_act doubleexp \
-p trainstage train_FSCIL \
-p dataset "" \
-p random_seed 7 \
-p learning_rate 0.01 \
-p lr_step_size 250 \
-p batch_size_training 256 \
-p batch_size_inference 256 \
-p num_query_training 0 \
-p optimizer SGD \
-p sharpening_activation softabs \
-p SGDnesterov True \
-p representation real \
-p retrain_act real \
-p num_ways 60 \
-p num_shots 15 \
-p block_architecture mini_resnet12 \
-p sample_num 400 \
-p gpu 0

